CREATE TABLE [dbo].[COMPANY_RECORD]
(
	[COMPANY_RECORD_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [EXCHANGE] VARCHAR(50) NOT NULL, 
    [NAME] VARCHAR(50) NOT NULL, 
    [URL_WEBSITE] VARCHAR(50) NULL, 
    [STOCK_TICKER] VARCHAR(50) NOT NULL, 
    [ISIN] VARCHAR(12) NOT NULL,
	CONSTRAINT UC_COMPANY UNIQUE ([COMPANY_RECORD_ID],[ISIN])
)



select * from [COMPANY_RECORD]